using Inari.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Inari.Services
{
    public interface IEmbeddingService<TTaskType>
        where TTaskType : Enum
    {
        /// <summary>
        /// Gets the vector value of the input string in the mode specified in <paramref name="taskType"/>.
        /// </summary>
        /// <param name="query">The content of the query.</param>
        /// <param name="title">The title of the document.</param>
        /// <param name="taskType">The task type.</param>
        /// <returns>The vector generated by AI embedding generator.</returns>
        /// <exception cref="ArgumentException">The <paramref name="query"/> is empty or only contains white spaces.</exception>
        /// <exception cref="ArgumentNullException">The <paramref name="query"/> is null.</exception>
        Task<float[]> GetVectorAsync(string query, string? title = null, TTaskType? taskType = default);

        /// <summary>
        /// Gets the match rate for every elements in the specified <paramref name="values"/> by using <paramref name="vectors"/>.
        /// </summary>
        /// <typeparam name="T">The type of values to be included in the result displaying object.</typeparam>
        /// <param name="query">The query string.</param>
        /// <param name="vectors">The preset vectors to be searched.</param>
        /// <param name="values">The raw values associated with each vector.</param>
        /// <returns>The tuple to specify the values and rank.</returns>
        /// <exception cref="ArgumentException"><paramref name="query"/> is empty or only contains white spaces.</exception>
        /// <exception cref="ArgumentNullException">One or more parameter(s) are null.</exception>
        /// <exception cref="InvalidOperationException">The numbers of the raw values and vectors do not match.</exception>
        IAsyncEnumerable<(T Value, float MatchRate, int Rank)> SearchAsync<T>(string query, IEnumerable<float[]> vectors, IEnumerable<T> values);
    }
}
